
# Introduction to relational databases

## Why use a relational database?

Here are some of the benefits of using a database to store your data - as opposed to a .csv, .xml, or any other file format:

- you can better manage access (e.g. you can set who is the admin, who can read, who can write, etc.)
- you can collaborate and have many parallel users using the data
- databases are designed to scale and handle large amount of data
- the database schema can be expanded
- relational database can also enforce certain standards such as having a unique value as primary key and thus avoid data quality issues
- relational databases can also enforce data type, e.g. a database can prevent someone from entering an invalid date or an number instead of a name, etc.

## Database schema

A relational database schema represents the connections between different sets of data each capture in a table.

In order to connect tables together, we use a key - also known as primary key - so that data from different takes can be matched. In Excel, you would use a VLOOKUP function to enrich a table with data from another table using a column that is shared amongst the two tables.

<img src="https://nico.nexgate.ch/images/schema.png" width='80%' />

Question: in the diagram above, what are the relationships between the 3 tables?

- 1:1 relationship (in other words 1 record from the 1st table is linked to 1 record from the 2nd table)
- 1:N relationship (in other words 1 record from 1 table is linked to many records of the 2nd talbe)
- N:N many records of the 1st table are linked to many records of the second table



## Parallel with Excel

<img src="https://nico.nexgate.ch/images/vlookup.png" width='100%' />

Question: what limitations do you see in using Excel and vlookup?

# Data storage

* step 1. go to http://data.world
* step 2. create an account or log in via  google
* step 3. search for "ZHAW" and select the Data Analysis Fundamentals dataset

<img src="https://nico.nexgate.ch/images/zhaw/dataworld (1).png" width='70%' />


* step 4. click on the "Data Analysis Fundamentals" link

then scroll down until you see the "Pirates" raw data and click to open it.

<img src="https://nico.nexgate.ch/images/zhaw/pirates.png" width='70%' />

The bottom right corner of the screen shows table columns of the Pirates dataset which you may regognize from the course.

<img src="https://nico.nexgate.ch/images/zhaw/pirates_table.png" width='70%' />


* step 5. click on Query 

<img src="https://nico.nexgate.ch/images/zhaw/query.png" width='70%' />

In [ ]:
import pandas as pd

# Accessing dataset hosted on data.world

## Accessing a table

### Swiss populations since from 1850 to 2015

In [1]:
import pandas as pd
# accessing a table hosted on data.world
df = pd.read_csv('https://query.data.world/s/5abh3qmxekqnegwbs5dndnlojtak5d?dws=00000',encoding='latin-1',sep=';') # latin-1 is one of the encoding of characters, for japaneese its different etc.

In [2]:
df.head()

,Année,No de la commune,Nom de la commune,No du district,Nom du district,No du canton,Canton,Nom du canton,Unité,Nombre
0,1850,1,Aeugst,101,Affoltern,1,ZH,Zürich,Habitants - Total,647.0
1,1850,1,Aeugst,101,Affoltern,1,ZH,Zürich,Nationalité - Suisse,646.0
2,1850,1,Aeugst,101,Affoltern,1,ZH,Zürich,Nationalité - Etranger,1.0
3,1850,1,Aeugst,101,Affoltern,1,ZH,Zürich,Sexe - Homme,320.0
4,1850,1,Aeugst,101,Affoltern,1,ZH,Zürich,Sexe - Femme,327.0

## Accessing a query

SQL stands for Structured Query Language. It is a query language which lets you interract with relational databases.

Using SQL, you can:

- filter data (equivalent to using one or several masks in python),
- group and aggregate data (equivalent to using groupby combined with an aggregation funciton in python)
- sort data (equivalent to using sort_values in pandas)
- and much more...

### Creating and saving your own database queries

Steps to create and save your query:

STEP 1: create your SQL query, click Download and choose Save to Dataset or Project

<img src="https://nico.nexgate.ch/images/zhaw/embed.png" width='50%' />


STEP 2: copy the link

<img src="https://nico.nexgate.ch/images/zhaw/copylink.png" width='50%' />

STEP 3: paste the link in your python code using 

for example: 

```pd.read_csv('https://download.data.world/s/gfzfssot6pvcag3t4qwflbplzc6uf5?dws=00000')```

### Retrieving the output form your SQL queries

#### Pirate table

```SQL
SELECT pirateid, firstname, lastname, shipid 
FROM pirate
```

In [3]:
df_pirates = pd.read_csv('https://download.data.world/s/zb3nv6d4yzd6woqdra4xrcnrxkksyv?dws=00000')

df_pirates.head(4)

   pirateid firstname    lastname  shipid
0         1  Francois         Nob      45
1         2      Pete        Smee      14
2         3      Bose  Threepwood      33
3         8    Hector        Dean      40

#### Ship table: basic select 

```SQL
SELECT shipid, shipname,maidenyear  
FROM ship
```

In [4]:
df_ships = pd.read_csv('https://download.data.world/s/ookb3sdvdy2tyfhqkzevlrbsbldiu2?dws=00000')

df_ships.head(4)

   shipid       shipname  maidenyear
0       1    Black Pearl        1659
1       2     Black Wind        1651
2       3         Dagger        1684
3       4  Dagon's Feast        1685

#### Pirates and ships

Select with condition (equivalent of a mask in Python)

Let's list the pirates that were on board the Black Peark.

First we get the ship id for the Black Pearl.

Then we list the pirates who were on a ship with that ship id.

In [5]:

df_ships[df_ships.shipname == 'Black Pearl']

   shipid     shipname  maidenyear
0       1  Black Pearl        1659

In [6]:
df_pirates[df_pirates.shipid == 1][['firstname', 'lastname']]

      firstname    lastname
72        Conan     Johnson
148         Jim  Threepwood
187        Gove     Sparrow
202       James        Curd
222        Nate       Jones
322        Davy    Albrecht
335    One-eyed        John
338        Gove     Sparrow
404        Bose      Liddle
494  Red-handed   Red-beard
500       James        Hook
510        Gove       Allen
522        Tony        Fozz
535        Tony        Curd
547      Bonnie       Jones
562        Doug  Threepwood
568        Jack        Ball
684       Mofit        Ball
692    Guybrush      Romney

In SQL, we can also filter a table

```SQL
SELECT firstname, lastname 
FROM pirate
WHERE shipid=1
```

In [7]:
df_pirates_on_black_pearl = pd.read_csv('https://download.data.world/s/tnt4w42gk2twm7rqnojl47bqtx2r5z?dws=00000')
df_pirates_on_black_pearl

     firstname    lastname
0        Conan     Johnson
1          Jim  Threepwood
2         Gove     Sparrow
3        James        Curd
4         Nate       Jones
5        James        Hook
6         Gove       Allen
7         Tony        Fozz
8         Tony        Curd
9       Bonnie       Jones
10        Doug  Threepwood
11        Jack        Ball
12       Mofit        Ball
13    Guybrush      Romney
14        Davy    Albrecht
15    One-eyed        John
16        Gove     Sparrow
17        Bose      Liddle
18  Red-handed   Red-beard

TODO: 

write a SQL query to find out the names of the ships which had their maiden journey in 1652

#### Joining tables

Let's enrich the pirate table by adding the ship's name

```SQL

SELECT s.shipname, p.firstname, p.lastname
FROM pirate p
JOIN ship s ON p.shipid = s.shipid
ORDER BY s.shipname
```

In [8]:
df_crew = pd.read_csv('https://download.data.world/s/wkcwiahzvskno2usawaz4xmcxo7fim?dws=00000')

df_crew.head(4)

      shipname firstname lastname
0  Black Pearl     James     Hook
1  Black Pearl      Gove    Allen
2  Black Pearl      Tony     Fozz
3  Black Pearl  Guybrush   Romney

TODO:

write a SQL query to find out all the locaiotns where the ship White Widow was involved.

hint: the tables are "encounter" and "ship"


#### Pirate table: min, max, avg

```SQL
SELECT
    MIN(limbs) AS min_limbs,
    MAX(limbs) AS max_limbs,
    AVG(limbs) AS avg_limbs
FROM pirate
```

In [9]:
import pandas as pd
df = pd.read_csv('https://download.data.world/s/zz24e2k7yxbuety4p6gfdgeo3gwert?dws=00000')
df

   min_limbs  max_limbs  avg_limbs
0        0.0        4.0   3.207835

#### Swiss cities table

languages spoken in Horgen in 2000

```SQL
SELECT DISTINCT unite
FROM su_f_01_01_vz1850_ge_01 
WHERE unite LIKE "Langue %"
AND nom_du_district = "Horgen"
AND annee = 2000
```

In [10]:
import pandas as pd
df3 = pd.read_csv('https://download.data.world/s/x3dqtwixurjk2engbpoaz6sa5tla5c?dws=00000')
df3.head()

                           unite
0              Langue - Romanche
1              Langue - Français
2   Langue - Italien (harmonisé)
3  Langue - Romanche (harmonisé)
4              Langue - Allemand

 #### kandidierende table (2023 Swiss elections dataset)



 Federal elections were held in Switzerland on 22 October 2023 to elect all members of the National Council and Council of States. This dataset contains the list of candidates, their political party, dob, occupation, etc.

10 cantons with the least number of cantidates

```SQL
SELECT kanton_bezeichnung Canton, COUNT(*) as name_count
FROM kandidierende
GROUP BY Canton
ORDER BY name_count ASC
LIMIT 10;
```

In [11]:
df4 = pd.read_csv('https://download.data.world/s/2q65fulimnccon5oakitos2s4y2ain?dws=00000')

In [12]:
df4

                   Canton  name_count
0   Appenzell Innerrhoden           2
1                Obwalden           2
2               Nidwalden           3
3                     Uri           3
4  Appenzell Ausserrhoden           4
5                  Glarus           5
6                    Jura          34
7            Schaffhausen          38
8               Neuchâtel          59
9                     Zug          99

# Optional material for your project

## Combining data from multiple dataframes

First you need to think about how you want to combine the data.

Here are some 2 ways of combining data:

---- to combine one data frame to another data frame

### "vlookup-style" enrichment

This is similar to doing a vlookup in Excel to add 1 or several columns of data from another table. -> use the Pandas funciton merge:


```Python
pd.merge(df1,df2,left_on='left_key', right_on='right_key')
```

Note: lookup the documentation. there are a lot more options such as using "how" to define if you want an inner join, an outter join, a left or a right join.

### stack them on top of each other

You have multiple files with exactly the same column headers and no data overlap. For instance, you have an employee list from employees in Switzerland, and another employee list from employees outside of Switzerland -> use the Pandas funciton concat:

```Python
pd.concat(([df1,df2]))
```

note: if the indexes of your dataframes overlap, then you can add another parameter to ignore the overlap and treat each line of data as a new line (even if it has the same index number in df1 and df2), e.g.

```Python
pd.concat([df1,df2], ignore_index=True)
```

## Avoiding errors when changing values


It is very common to get an error when one tries to modify some values in a dataframe.

Typically, one would get an error like the one below:

```
/tmp/ipykernel_7254/3546892955.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead
```
  
Frustrating as it may, it can be resolved relatively easily, let's look at it!

In [13]:
df = pd.read_csv('https://query.data.world/s/5abh3qmxekqnegwbs5dndnlojtak5d?dws=00000',encoding='latin-1',sep=';')

In [14]:
df.head(3)

,Année,No de la commune,Nom de la commune,No du district,Nom du district,No du canton,Canton,Nom du canton,Unité,Nombre
0,1850,1,Aeugst,101,Affoltern,1,ZH,Zürich,Habitants - Total,647.0
1,1850,1,Aeugst,101,Affoltern,1,ZH,Zürich,Nationalité - Suisse,646.0
2,1850,1,Aeugst,101,Affoltern,1,ZH,Zürich,Nationalité - Etranger,1.0

In [15]:
# let's create a mask to filter data for 1 city in canton Zurich:

mask = df['Nom de la commune'] == 'Aeugst am Albis'

In [16]:

# let's imagine we want to change the "No du district" for all rows which are in the city of Aeugst am Albis and set the new value to 999

# if you run this code, you will get an error message
df[mask]['No du district']= 999

C:\Users\pasca_p\AppData\Local\Temp\ipykernel_5976\1775732747.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[mask]['No du district']= 999

The reason is that we filtered view is actually an in-memory copy of a portion of the dataframe.

In other words, we are asking Pandas to show us specific rows of data using a mask. The output does not point to the same memory location used to store the orignal dataframe. Pandas allocates a new space in memory to store the filtered rows.

Thus, when you try to assign a new value to these rows, you get an error because you can't modify the original dataframe since you are pointing to a different place in memory.

So, how do I fix it?

you need to use the .loc funciton with 2 parameters within square brackets "[]":

- the 1st parameter is your mask -> it indicates the range of rows you want to modify
- the 2nd parameter is the column(s) you want to modify

You then you the equal sign "=" to asssign the new value(s). In our example the value 999.

see the code below:

In [17]:
# set the "no du district to 999 for all rows which are in the city of Aeugst am Albis"

df.loc[mask,'No du district'] = 999

In [18]:
# let's verify the output

df[mask].head(3)

,Année,No de la commune,Nom de la commune,No du district,Nom du district,No du canton,Canton,Nom du canton,Unité,Nombre
782600,1980,1,Aeugst am Albis,999,Affoltern,1,ZH,Zürich,Population résidante - Total,866.0
782601,1980,1,Aeugst am Albis,999,Affoltern,1,ZH,Zürich,Nationalité - Suisse,832.0
782602,1980,1,Aeugst am Albis,999,Affoltern,1,ZH,Zürich,Nationalité - Etranger,34.0